name: Selenium Tests

on:
  push:
    branches:
      - main  # Run tests when pushing to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # You can use ubuntu-latest, windows-latest for Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean test -DsuiteXmlFile=testng.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/*.xml
